### PR TITLE
fixed #1 modified: cmd/giita/post.go

### LINKED ISSUE #1: タグ不具合
↓下記コマンド打ったのにタグが `iita` になってしまいました。

```
giita post myTest.md -tags=giita -title="giita使ってみた"
```

修正お願いいたします。

### PR DESCRIPTION
**Pull request by kentokento**
This is `TrimLeft`'s bug...orz

### CODE REVIEW

**Comment by kaneshin** [comment]
Hi, @kentokento 

Which version do you use?
Let me know your go version. Just type like this `go version` then show up your version on terminal.

Thx.

**Comment by kentokento** [comment]
Dear @kaneshin 

The following is version.

```
[kento ~]$ go version
go version go1.4.2 darwin/amd64
```

This issue is problem on me...?

**Comment by kaneshin** [comment]
Wow, this bug is related in go.
I've tried some case in go playground. http://play.golang.org/p/udVTG_f-Rt

Thanks!

**Comment by kentokento** [comment]
yeehaw!! graet!

This problem Let's call ... "trim panic" !

Thx.

**Pull request merged**
